-- Intelligence pipeline + Strategic reports (isolated from news table)

CREATE TABLE IF NOT EXISTS `intelligence_source_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_api` ENUM('nyt', 'guardian', 'rss') NOT NULL,
  `external_id` VARCHAR(255) NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `published_at` DATETIME NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` TEXT NULL,
  `raw_content` LONGTEXT NULL,
  `clean_text` LONGTEXT NULL,
  `word_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `quality_score` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `duplicate_of` INT UNSIGNED NULL,
  `merged_source_ids` JSON NULL,
  `region` JSON NULL,
  `topic` JSON NULL,
  `event_type` VARCHAR(50) NULL,
  `entities` JSON NULL,
  `relevance_score` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `trust_tier` ENUM('A', 'B', 'C') NOT NULL DEFAULT 'B',
  `fetch_status` ENUM('pending', 'fetched', 'failed', 'skipped') NOT NULL DEFAULT 'pending',
  `clean_status` ENUM('pending', 'done', 'failed') NOT NULL DEFAULT 'pending',
  `categorize_status` ENUM('pending', 'done', 'failed') NOT NULL DEFAULT 'pending',
  `embed_status` ENUM('pending', 'done', 'failed', 'skipped') NOT NULL DEFAULT 'pending',
  `chunk_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `pipeline_errors` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_source_external` (`source_api`, `external_id`),
  KEY `idx_published` (`published_at` DESC),
  KEY `idx_pipeline` (`fetch_status`, `clean_status`, `categorize_status`, `embed_status`),
  KEY `idx_relevance` (`relevance_score` DESC),
  KEY `idx_duplicate` (`duplicate_of`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `weekly_strategic_reports` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `report_week` VARCHAR(10) NOT NULL,
  `period_start` DATE NOT NULL,
  `period_end` DATE NOT NULL,
  `executive_summary` TEXT NULL,
  `scqa_raw_json` JSON NOT NULL,
  `scqa_edited_json` JSON NULL,
  `edit_diff_json` JSON NULL,
  `edit_reason` TEXT NULL,
  `judgment_feedbacks` JSON NULL,
  `source_articles_json` JSON NULL,
  `meta_json` JSON NULL,
  `status` ENUM('draft', 'reviewed', 'approved') NOT NULL DEFAULT 'draft',
  `confidence` ENUM('high', 'medium', 'low') NOT NULL DEFAULT 'medium',
  `editor_notes` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_report_week` (`report_week`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
