<?php
/**
 * GIST EDU 부모 리포트 샘플 5 — PDF 생성용 데이터 (Editorial Orange v3.1)
 * @see docs/GIST_EDU_PARENT_REPORT_SAMPLES.md
 */
return [
    [
        'filename' => '01_김민준_중2_Q-G01_AI일자리안전망.pdf',
        'student_name' => '김민준',
        'grade_label' => '중학교 2학년',
        'quest_code' => 'Q-G01',
        'quest_title' => '정부는 AI 일자리 대란 전에 안전망을 깔아야 할까?',
        'period' => '2026-05-12 ~ 2026-05-18',
        'period_label' => '2026년 5월 · 1주 활동',
        'parent_story' => '뉴스 복붙이 아니라, 찬반을 구조로 쓰기 시작했습니다.',
        'lead_kicker' => '이달의 핵심 순간',
        'lead_headline' => '민준이가 이번 달,',
        'lead_headline_em' => '생각을 깊게 다졌습니다.',
        'share_card' => [
            'kicker' => '이번 달 가장 큰 변화',
            'before' => '"AI 좋은 거니까 규제 말자."',
            'after' => '"일자리가 바뀌면 정부가 미리 안전망을 깔아야 한다."',
        ],
        'transform' => [
            'before_time' => '한 달 전',
            'before_stance' => '찬성 입장',
            'before_text' => '"AI 좋은 거니까 규제 말자."',
            'before_sub' => '근거 없음 · 직관적 반응',
            'after_time' => '이번 주',
            'after_stance' => '입장 정교화',
            'after_text' => '"일자리가 바뀌면 정부가 미리 안전망을 깔아야 한다."',
            'after_sub' => '근거 2개 인용 · 반론 수용 후 수정',
        ],
        'narrative_paragraphs' => [
            '민준은 처음에 "AI는 좋으니 규제하지 말자"는 직관에서 출발했습니다. 그런데 고용지표만으로 안심하면 안 된다는 기사와, 아직 대규모 실업은 없다는 반론을 읽고 — 전면 규제 대신 재교육·안전망 쪽으로 입장을 정교화했습니다.',
            'v1에서 4번과 5번이 모순이었던 글이, v2에서는 주장-근거-반론-결론 구조로 정리되었습니다. 이것은 단순히 더 좋은 답을 찾은 것이 아니라, <b>근거를 붙이고 모순을 스스로 고치는 힘이 생겼다는 신호</b>입니다.',
        ],
        'monthly_first_changes' => [
            '기사 근거를 처음 인용했습니다.',
            '반대 의견을 검토한 뒤 입장을 정교화했습니다.',
            '주장과 결론의 모순을 스스로 고쳤습니다.',
        ],
        'monthly_eval' => '민준은 "규제는 싫다"와 "찬성이다"가 함께 있던 글에서, 근거와 반론이 달린 구조로 바꾸기 시작했습니다. 반론을 읽고도 입장을 유지하되, 더 구체적으로 만드는 모습이 보였습니다.',
        'tier_progress' => [
            'tier_id' => 'gold',
            'tier_label_en' => 'Gold',
            'tier_label_ko' => '골드 사상가',
            'next_tier_id' => 'platinum',
            'next_tier_label_en' => 'Platinum',
            'xp_current' => 1440,
            'xp_next_tier' => 1800,
            'progress_pct' => 64,
            'streak_days' => 12,
            'show_quest_cta' => false,
        ],
        'parent_alert' => [
            'event' => 'tier_promotion',
            'title' => 'Gold 달성',
            'body' => '민준이가 Gold가 됐습니다. 이번 달 직접 쓴 문장 — "그래서 나는 전면 규제가 아니라 재교육·안전망 쪽에 찬성한다." 지난 6주 동안 입장을 5번 바꾸고 근거를 15번 인용했습니다.',
            'stats_window' => '6주',
            'stance_changes' => 5,
            'evidence_cites' => 15,
        ],
        'growth_card' => [
            'rows' => [
                ['label' => '입장', 'before' => 'AI 좋은 거니까 규제 말자', 'after' => '일자리 바뀌면 정부가 미리 준비해야', 'change' => 'refined'],
                ['label' => '근거 수', 'before' => '0', 'after' => '2 (기사 507, 72)', 'change' => '+2'],
                ['label' => '반론 인지', 'before' => '없음', 'after' => '지금 실업 없다 (한 줄)', 'change' => '✓'],
                ['label' => '일치·불일치', 'before' => '없음', 'after' => '위험 인정 / 안전망 vs 성장', 'change' => '✓'],
            ],
        ],
        'writing_growth' => [
            'v1_sentences' => [
                '나는 AI가 일자리를 없앤다고 생각한다.',
                '그래서 정부가 돈을 줘야 한다.',
                '친구 아빠도 걱정한다.',
                '규제는 싫다.',
                '그래도 찬성이다.',
            ],
            'teacher_feedback' => '2번 근거 없음, 4번과 5번 모순.',
            'v2_sentences' => [
                '나는 AI로 일자리가 바뀔 수 있어서 정부가 미리 안전망을 깔아야 한다고 본다.',
                'GIST 기사(507)는 고용지표만으로 안심하면 안 된다고 말한다.',
                '반대편은 아직 대규모 실업이 없으니 성장을 해치는 규제는 이르다고 한다.',
                '우리 가족도 AI 때문에 직업이 바뀔 수 있어 삶과 연결된다.',
                '그래서 나는 전면 규제가 아니라 재교육·안전망 쪽에 찬성한다.',
            ],
            'delta' => '근거·반론·입장 정교화. 모순 해소.',
        ],
        'qualitative_growth' => [
            ['label' => '구조화 능력 향상', 'detail' => '주장-근거-결론 구분이 뚜렷해짐. v1의 모순(4번·5번)이 v2에서 해소됨.'],
            ['label' => '근거 사용 증가', 'detail' => '기사 인용 0회 → 2회 (507, 72). 감정만 있던 주장에 출처가 붙음.'],
            ['label' => '반론 수용 증가', 'detail' => '반대 입장("지금 실업 없다")을 한 줄로 요약하고, 전면 규제 대신 재교육·안전망으로 입장을 정교화함.'],
        ],
    ],
    [
        'filename' => '02_이서연_중3_Q-G05_기후전환.pdf',
        'student_name' => '이서연',
        'grade_label' => '중학교 3학년',
        'quest_code' => 'Q-G05',
        'quest_title' => '기후 때문에 지금 당장 석유·가스를 줄여야 할까?',
        'period' => '2026-05-19 ~ 2026-05-25',
        'period_label' => '2026년 5월 · 1주 활동',
        'parent_story' => '환경 입장이 근거·반론 달린 글로 바뀌었습니다.',
        'lead_kicker' => '이달의 핵심 순간',
        'lead_headline' => '서연이가 이번 달,',
        'lead_headline_em' => '조건부로 생각하기 시작했습니다.',
        'share_card' => [
            'kicker' => '이번 달 가장 큰 변화',
            'before' => '"환경 중요, 당장 석유·가스 다 끊자."',
            'after' => '"빨리 줄이되, 당장 일자리·물가도 봐야 한다."',
        ],
        'transform' => [
            'before_time' => '한 달 전',
            'before_stance' => '극단 찬성',
            'before_text' => '"환경 중요, 당장 석유·가스 다 끊자."',
            'before_sub' => '감정 1줄 · 반론 무시',
            'after_time' => '이번 주',
            'after_stance' => '조건부 찬성',
            'after_text' => '"빨리 줄이되, 당장 일자리·물가도 봐야 한다."',
            'after_sub' => '기사 240, 291 인용 · 점진 전환 반론 수용',
        ],
        'narrative_paragraphs' => [
            '서연은 처음에 "환경이 위험하니 당장 다 끊자"는 감정적 입장에서 출발했습니다. 재생만으로 당장 가스를 없애기 어렵다는 기사와, 걸프국도 전환 중이라는 기사를 읽고 — 극단 찬성에서 조건부 찬성으로 수정했습니다.',
            '반대 의견을 "이기적"이라고 치부하던 습관이 줄었고, <b>근거와 반론이 달린 글</b>로 환경 입장을 쓰기 시작했습니다.',
        ],
        'monthly_first_changes' => [
            '기사 근거를 처음 인용했습니다.',
            '반대 의견을 검토한 뒤 입장을 수정했습니다.',
            '환경 감정 한 줄에서 조건과 근거가 달린 글로 바꿨습니다.',
        ],
        'monthly_eval' => '서연은 "당장 다 끊자"는 감정적 입장에서, 일자리와 물가를 함께 보는 조건부 찬성으로 바꾸기 시작했습니다. 반론을 무시하던 습관이 줄고, 근거가 붙은 글을 쓰는 모습이 보였습니다.',
        'tier_progress' => [
            'tier_id' => 'silver',
            'tier_label_en' => 'Silver',
            'tier_label_ko' => '실버',
            'next_tier_id' => 'gold',
            'next_tier_label_en' => 'Gold',
            'xp_current' => 1050,
            'xp_next_tier' => 1200,
            'progress_pct' => 33,
            'streak_days' => 8,
            'show_quest_cta' => false,
        ],
        'parent_alert' => null,
        'growth_card' => [
            'rows' => [
                ['label' => '입장', 'before' => '환경 중요, 당장 다 끊자', 'after' => '빨리 줄이되 일자리·물가도 봐야', 'change' => 'refined'],
                ['label' => '근거', 'before' => '감정 1', 'after' => '기사 240, 291', 'change' => '+구조'],
                ['label' => '반론', 'before' => '무시', 'after' => '점진 전환 요약', 'change' => '✓'],
            ],
        ],
        'writing_growth' => [
            'v1_sentences' => [
                '기후가 위험하다.',
                '석유를 당장 없애야 한다.',
                '정부가 나서야 한다.',
                '반대 의견은 이기적이다.',
                '그래서 전면 전환을 찬성한다.',
            ],
            'v2_sentences' => [
                '재생만으로 당장 가스를 없애기는 어렵지만, 걸프국도 전환 중이라 지금 투자를 미루면 안 된다.',
                '기사 240은 당장 끊기 어렵다는 점을, 291은 전환 투자 필요성을 말한다.',
                '반대편은 점진 전환이 일자리·물가를 보호한다고 한다.',
                '환경과 경제를 동시에 봐야 한다.',
                '그래서 나는 조건부 찬성으로 입장을 수정했다.',
            ],
            'delta' => '극단 찬성 → 조건부 찬성. 근거 2개 인용.',
        ],
        'qualitative_growth' => [
            ['label' => '구조화 능력 향상', 'detail' => '환경 감정 1줄에서 주장-근거-조건부 결론 구조로 전환됨.'],
            ['label' => '근거 사용 증가', 'detail' => '기사 240, 291을 인용해 "당장 끊기"에서 "투자 시점" 논의로 심화함.'],
            ['label' => '반론 수용 증가', 'detail' => '점진 전환 반론을 무시하지 않고, 극단 찬성 → 조건부 찬성으로 수정함.'],
        ],
    ],
    [
        'filename' => '03_박지훈_고1_Q-G14_대만위기.pdf',
        'student_name' => '박지훈',
        'grade_label' => '고등학교 1학년',
        'quest_code' => 'Q-G14',
        'quest_title' => '대만 위기 때 미국이 군사 개입해야 할까?',
        'period' => '2026-05-05 ~ 2026-05-11',
        'period_label' => '2026년 5월 · 1주 활동',
        'parent_story' => '대만 이슈를 일상이 아니라 함의까지 썼습니다.',
        'lead_kicker' => '이달의 핵심 순간',
        'lead_headline' => '지훈이가 이번 달,',
        'lead_headline_em' => '함의까지 쓰기 시작했습니다.',
        'share_card' => [
            'kicker' => '이번 달 가장 큰 변화',
            'before' => '"미국이 무조건 도와야 한다."',
            'after' => '"개입 여지는 필요하지만, 전쟁 비용이 크면 외교가 우선이다."',
        ],
        'transform' => [
            'before_time' => '한 달 전',
            'before_stance' => '단선적 찬성',
            'before_text' => '"미국이 무조건 도와야 한다."',
            'before_sub' => '감정 1건 · 반론 없음',
            'after_time' => '이번 주',
            'after_stance' => '조건부 찬성',
            'after_text' => '"개입 여지는 필요하지만, 전쟁 비용이 크면 외교가 우선이다."',
            'after_sub' => '기사 514 인용 · 521 반론 수용',
        ],
        'narrative_paragraphs' => [
            '지훈은 처음에 "미국이 무조건 도와야 한다"는 단선적 찬성에서 출발했습니다. 해협 긴장이 공급망에 직결된다는 기사와, 세력권 현실 수용이 전쟁을 막는다는 반론을 읽고 — 조건부 찬성과 한국 경제 함의까지 글에 담았습니다.',
            '국제 이슈를 일상과 연결하는 시도가 보입니다. <b>단순 찬반을 넘어 "그래서 우리에게 무엇이냐"를 쓰기 시작했다는 신호</b>입니다.',
        ],
        'monthly_first_changes' => [
            '기사 근거를 처음 인용했습니다.',
            '반대 의견을 검토한 뒤 입장을 수정했습니다.',
            '국제 이슈를 한국 경제와 연결해 설명했습니다.',
        ],
        'monthly_eval' => '지훈은 이번 달 단순한 찬반을 넘어, 국제 이슈가 한국 경제에 미치는 영향을 설명하기 시작했습니다. 새로운 근거를 받아들이며 자신의 생각을 더 정교하게 만드는 모습이 보였습니다.',
        'tier_progress' => [
            'tier_id' => 'gold',
            'tier_label_en' => 'Gold',
            'tier_label_ko' => '골드 사상가',
            'next_tier_id' => 'platinum',
            'next_tier_label_en' => 'Platinum',
            'xp_current' => 1580,
            'xp_next_tier' => 1800,
            'progress_pct' => 78,
            'streak_days' => 15,
            'show_quest_cta' => false,
        ],
        'parent_alert' => null,
        'growth_card' => [
            'rows' => [
                ['label' => '입장', 'before' => '미국 무조건 도와야', 'after' => '개입 여지 필요, 전쟁 비용 크면 외교 우선', 'change' => 'refined'],
                ['label' => '근거', 'before' => '1 (감정)', 'after' => '514 공급망', 'change' => '+기사'],
                ['label' => '반론', 'before' => '없음', 'after' => '521 세력권 현실 수용', 'change' => '✓'],
            ],
        ],
        'writing_growth' => [
            'v1_sentences' => [
                '대만을 지켜야 한다.',
                '미국이 도와야 한다.',
                '반도체가 중요하다.',
                '중국이 나쁘다.',
                '그래서 개입 찬성.',
            ],
            'v2_sentences' => [
                '반도체·동맹 때문에 미국 개입 여지는 필요하지만, 전쟁 비용이 너무 크면 외교가 우선이다.',
                '기사 514는 해협 긴장이 공급망에 직결된다고 말한다.',
                '반대편 521은 세력권 현실 수용이 전쟁을 막는다고 본다.',
                '한국 경제도 공급망 충격에 취약하다.',
                '그래서 무조건 개입보다 조건부 찬성과 함의 서술이 맞다.',
            ],
            'delta' => '단선적 찬성 → 조건부 찬성 + 함의.',
        ],
        'qualitative_growth' => [
            ['label' => '구조화 능력 향상', 'detail' => '단선적 찬성에서 조건부 찬성 + 함의 서술로 전환. 일상과 국제 이슈를 연결함.'],
            ['label' => '근거 사용 증가', 'detail' => '감정 1건 → 기사 514(공급망) 인용. 한국 경제 함의까지 확장함.'],
            ['label' => '반론 수용 증가', 'detail' => '기사 521(세력권 현실 수용)을 반영해 "무조건 개입"에서 "외교 우선 조건"으로 수정함.'],
        ],
    ],
    [
        'filename' => '04_최유나_고2_Q-G17_금리물가.pdf',
        'student_name' => '최유나',
        'grade_label' => '고등학교 2학년',
        'quest_code' => 'Q-G17',
        'quest_title' => '물가 잡으려면 지금 금리를 더 오래 높게 유지해야 할까?',
        'period' => '2026-04-28 ~ 2026-05-04',
        'period_label' => '2026년 5월 · 4주 활동',
        'parent_story' => '물가 글에서 입장을 바꾼 이유를 설명했습니다.',
        'lead_kicker' => '이달의 핵심 순간',
        'lead_headline' => '유나가 이번 달,',
        'lead_headline_em' => '생각을 바꿨습니다.',
        'share_card' => [
            'kicker' => '이번 달 가장 큰 변화',
            'before' => '"금리를 올리면 대출이 부담된다. 그래서 반대한다."',
            'after' => '"단기 고통이 있어도 인플레 기대를 잡으려면 고금리 유지가 필요할 수 있다."',
        ],
        'transform' => [
            'before_time' => '한 달 전',
            'before_stance' => '반대 입장',
            'before_text' => '"금리를 올리면 대출이 부담된다. 그래서 반대한다."',
            'before_sub' => '근거 없음 · 직관적 반응',
            'after_time' => '이번 주',
            'after_stance' => '찬성으로 전환',
            'after_text' => '"단기 고통이 있어도 인플레 기대를 잡으려면 고금리 유지가 필요할 수 있다."',
            'after_sub' => '근거 2개 인용 · 반론 수용 후 전환',
        ],
        'narrative_paragraphs' => [
            '유나는 처음에 "금리를 올리면 사람들이 힘들어진다"는 직관적인 입장에서 출발했습니다. AI·전력 수요로 인한 구조적 물가 압력 기사를 읽고, 실업과 경기 침체라는 반론까지 직접 검토한 뒤 — 결국 스스로 입장을 바꾸었습니다.',
            '이것은 단순히 더 좋은 답을 찾은 것이 아닙니다. <b>새로운 근거를 받아들이고, 자신의 결론을 스스로 수정하는 힘이 생겼다는 신호입니다.</b> 처음에는 반대 의견을 거의 고려하지 않았던 유나가, 이번 달에는 실업률 증가라는 반론을 검토한 뒤 자신의 입장을 바꾸었습니다.',
        ],
        'monthly_first_changes' => [
            '기사 근거를 처음 인용했습니다.',
            '반대 의견을 검토한 뒤 입장을 바꿨습니다.',
            '입장을 바꾼 이유를 5문장으로 설명했습니다.',
        ],
        'monthly_eval' => '유나는 "금리 올리면 힘들다"는 직관에서 출발해, 구조적 물가 압력을 인정하고 스스로 찬성으로 입장을 바꿨습니다. 반대 의견을 검토한 뒤 결론을 수정하는 모습이 보였습니다.',
        'tier_progress' => [
            'tier_id' => 'gold',
            'tier_label_en' => 'Gold',
            'tier_label_ko' => '골드 사상가',
            'next_tier_id' => 'platinum',
            'next_tier_label_en' => 'Platinum',
            'xp_current' => 1320,
            'xp_next_tier' => 1800,
            'progress_pct' => 22,
            'streak_days' => 6,
            'show_quest_cta' => false,
        ],
        'parent_alert' => [
            'event' => 'tier_promotion',
            'title' => 'Gold 달성',
            'body' => '유나가 Gold가 됐습니다. 이번 달 직접 쓴 문장 — "그래서 나는 반대에서 찬성으로 입장을 바꿨다." 지난 4주 동안 입장을 3번 바꾸고 근거를 11번 인용했습니다.',
            'stats_window' => '4주',
            'stance_changes' => 3,
            'evidence_cites' => 11,
        ],
        'growth_card' => [
            'rows' => [
                ['label' => '입장', 'before' => '금리 올리면 힘들다 → 반대', 'after' => '고금리 유지가 나을 수 있다', 'change' => 'flipped'],
                ['label' => '근거', 'before' => '0', 'after' => '150, 210', 'change' => '+2'],
                ['label' => '반론 인지', 'before' => '없음', 'after' => '실업·경기 우려', 'change' => '✓'],
            ],
        ],
        'writing_growth' => [
            'v1_sentences' => [
                '금리가 오르면 대출이 부담된다.',
                '그래서 금리 인상에 반대한다.',
                '물가도 문제다.',
                '정부가 뭔가 해야 한다.',
                '반대 입장이다.',
            ],
            'v2_sentences' => [
                '단기 고통이 있어도 인플레 기대를 잡으려면 고금리 유지가 필요할 수 있다.',
                '기사 150은 AI·전력 수요가 구조적 물가 압력이라고 본다.',
                '기사 210은 시장이 AI 영향을 아직 제대로 가격하지 못한다고 한다.',
                '반대편은 실업·경기 침체가 더 위험하다고 한다.',
                '그래서 나는 반대에서 찬성으로 입장을 바꿨다 (flipped).',
            ],
            'delta' => 'stance_delta: flipped — 구조적 인플레 인정 후 입장 전환.',
        ],
        'qualitative_growth' => [
            ['label' => '구조화 능력 향상', 'detail' => '단기 고통 vs 인플레 기대를 대비해 입장을 재구성함. flipped 이유를 5문장으로 설명함.'],
            ['label' => '근거 사용 증가', 'detail' => '기사 150(AI·전력 수요), 210(시장 불확실) 인용. 구조적 인플레를 인정하는 근거가 생김.'],
            ['label' => '반론 수용 증가', 'detail' => '실업·경기 우려 반론을 인지한 뒤, 반대 → 찬성으로 입장을 바꿈 (stance_delta: flipped).'],
        ],
    ],
    [
        'filename' => '05_정하은_고3_Q-G20_인지적항복.pdf',
        'student_name' => '정하은',
        'grade_label' => '고등학교 3학년',
        'quest_code' => 'Q-G20',
        'quest_title' => '직장에서 AI에게 \'생각\'을 맡기는 것까지 허용해야 할까?',
        'period' => '2026-05-26 ~ 2026-06-01',
        'period_label' => '2026년 6월 · 1주 활동',
        'parent_story' => '지스트 원문 수준으로 일치·불일치를 써 냈습니다.',
        'lead_kicker' => '이달의 핵심 순간',
        'lead_headline' => '하은이가 이번 달,',
        'lead_headline_em' => 'GIST Challenger에 도달했습니다.',
        'share_card' => [
            'kicker' => '이번 달 가장 큰 변화',
            'before' => '"AI 쓰면 효율, 전부 OK."',
            'after' => '"보조는 OK, 최종 판단·책임은 사람 — 인지적 항복 경계."',
        ],
        'transform' => [
            'before_time' => '한 달 전',
            'before_stance' => '전면 찬성',
            'before_text' => '"AI 쓰면 효율, 전부 OK."',
            'before_sub' => '일치·불일치 없음',
            'after_time' => '이번 주',
            'after_stance' => '조건부 찬성',
            'after_text' => '"보조는 OK, 최종 판단·책임은 사람 — 인지적 항복 경계."',
            'after_sub' => '기사 462 인용 · KPI vs 비판적 사고 충돌 인지',
        ],
        'narrative_paragraphs' => [
            '하은은 처음에 "AI를 쓰면 빨라지니 전부 OK"라는 입장에서 출발했습니다. AI가 인지적 항복을 초래할 수 있다는 기사와, 효율 이점은 공통이지만 KPI 자동화와 비판적 사고 사이에 충돌이 있다는 분석을 읽고 — 최종 판단과 책임은 사람에게 있어야 한다고 썼습니다.',
            '여러 기사의 <b>일치·불일치를 GIST 원문 수준으로 서술</b>했습니다. GIST Challenger 슬롯을 한 번 완료한 기록입니다.',
        ],
        'monthly_first_changes' => [
            '기사 근거를 처음 인용했습니다.',
            '여러 기사의 일치·불일치를 구조로 썼습니다.',
            'AI 효율과 인지적 항복 사이의 충돌을 스스로 정리했습니다.',
        ],
        'monthly_eval' => '하은은 "AI를 쓰면 다 OK"에서, 최종 판단과 책임은 사람에게 있다는 입장으로 정교화했습니다. GIST 원문 수준의 일치·불일치 서술로 Challenger 슬롯을 완료했습니다.',
        'tier_progress' => [
            'tier_id' => 'gist_challenger',
            'tier_label_en' => 'GIST Challenger',
            'tier_label_ko' => 'GIST 챌린저',
            'next_tier_id' => null,
            'next_tier_label_en' => null,
            'xp_current' => 2680,
            'xp_next_tier' => null,
            'progress_pct' => 100,
            'streak_days' => 24,
            'show_quest_cta' => false,
        ],
        'parent_alert' => [
            'event' => 'gist_challenger',
            'title' => 'GIST Challenger 달성',
            'body' => '하은이가 GIST Challenger가 됐습니다. 직접 쓴 문장 — "AI 보조는 생산성에 도움이 되지만, 최종 판단과 책임은 사람에게 있어야 한다." GIST가 인정하는 최고 등급입니다. 2년간 입장을 120번 수정하고 전국 퀘스트를 10번 완주했습니다.',
            'stats_window' => '2년',
            'stance_changes' => 120,
            'quests_completed' => 10,
        ],
        'growth_card' => [
            'rows' => [
                ['label' => '입장', 'before' => 'AI 쓰면 효율, 전부 OK', 'after' => '보조 OK, 최종 판단·책임은 사람', 'change' => 'refined'],
                ['label' => '일치·불일치', 'before' => '없음', 'after' => '효율 공통 / KPI vs 비판적 사고', 'change' => '✓'],
            ],
        ],
        'writing_growth' => [
            'v1_sentences' => [
                'AI를 쓰면 일이 빨라진다.',
                '회사도 AI를 써야 한다.',
                '안 쓰면 뒤처진다.',
                '규제는 필요 없다.',
                '적극 찬성한다.',
            ],
            'v2_sentences' => [
                'AI 보조는 생산성에 도움이 되지만, 최종 판단과 책임은 사람에게 있어야 한다.',
                '기사 462는 AI가 인지적 항복을 초래할 수 있다고 경고한다.',
                '여러 기사는 효율·생산성 이점을 공통으로 본다 (일치).',
                '충돌은 KPI 자동화 vs 비판적 사고 유지 사이에 있다.',
                '진로(경영·IT)에서 검증 습관이 차별점이 될 것이다.',
            ],
            'delta' => 'GIST Challenger 슬롯 1회 완료.',
            'challenger_slots' => [
                'gist_quote' => 'news_id 462 — AI는 인지적 항복을 초래할 수 있다',
                'core_alignment' => '효율·생산성 이점은 여러 기사 공통',
                'core_conflict' => 'KPI 자동화 vs 비판적 사고 유지',
                'so_what' => '진로(경영·IT)에서 검증 습관이 차별점',
            ],
        ],
        'qualitative_growth' => [
            ['label' => '구조화 능력 향상', 'detail' => '일치·불일치를 GIST 원문 수준으로 서술. gist_quote·core_alignment·core_conflict 슬롯 완성.'],
            ['label' => '근거 사용 증가', 'detail' => 'news_id 462 인용 및 여러 기사 간 일치점을 구조화함.'],
            ['label' => '반론 수용 증가', 'detail' => 'KPI 자동화 vs 비판적 사고 충돌을 인지하고, 최종 판단·책임은 사람에게 있다고 명시함.'],
        ],
    ],
];
